################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/BSP/Camera \
Drivers/BSP/Gpio \
Drivers/BSP/Misc \
Drivers/BSP/Pwm \
Drivers/BSP/Rtc \
Drivers/BSP/ST7735 \
Drivers/BSP/W25QXX \
Drivers/STM32H7xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/esp_hosted/common \
Middlewares/Third_Party/esp_hosted/common/protobuf-c/protobuf-c \
Middlewares/Third_Party/esp_hosted/host/components/src \
Middlewares/Third_Party/esp_hosted/host/control_lib/src \
Middlewares/Third_Party/esp_hosted/host/stm32/app \
Middlewares/Third_Party/esp_hosted/host/stm32/app/control \
Middlewares/Third_Party/esp_hosted/host/stm32/app/data \
Middlewares/Third_Party/esp_hosted/host/stm32/common \
Middlewares/Third_Party/esp_hosted/host/stm32/driver/network \
Middlewares/Third_Party/esp_hosted/host/stm32/driver/serial \
Middlewares/Third_Party/esp_hosted/host/stm32/driver/transport/spi \
Middlewares/Third_Party/esp_hosted/host/stm32/driver/transport \
Middlewares/Third_Party/esp_hosted/host/stm32/port/src \
Middlewares/Third_Party/esp_hosted/host/virtual_serial_if/src \
tinyusb/src/class/audio \
tinyusb/src/class/bth \
tinyusb/src/class/cdc \
tinyusb/src/class/dfu \
tinyusb/src/class/hid \
tinyusb/src/class/midi \
tinyusb/src/class/msc \
tinyusb/src/class/net \
tinyusb/src/class/usbtmc \
tinyusb/src/class/vendor \
tinyusb/src/class/video \
tinyusb/src/common \
tinyusb/src/device \
tinyusb/src/host \
tinyusb/src/portable/analog/max3421 \
tinyusb/src/portable/bridgetek/ft9xx \
tinyusb/src/portable/chipidea/ci_fs \
tinyusb/src/portable/chipidea/ci_hs \
tinyusb/src/portable/dialog/da146xx \
tinyusb/src/portable/ehci \
tinyusb/src/portable/espressif/esp32sx \
tinyusb/src/portable/mentor/musb \
tinyusb/src/portable/microchip/pic \
tinyusb/src/portable/microchip/pic32mz \
tinyusb/src/portable/microchip/samd \
tinyusb/src/portable/microchip/samg \
tinyusb/src/portable/microchip/samx7x \
tinyusb/src/portable/mindmotion/mm32 \
tinyusb/src/portable/nordic/nrf5x \
tinyusb/src/portable/nuvoton/nuc120 \
tinyusb/src/portable/nuvoton/nuc121 \
tinyusb/src/portable/nuvoton/nuc505 \
tinyusb/src/portable/nxp/khci \
tinyusb/src/portable/nxp/lpc17_40 \
tinyusb/src/portable/nxp/lpc_ip3511 \
tinyusb/src/portable/ohci \
tinyusb/src/portable/raspberrypi/pio_usb \
tinyusb/src/portable/raspberrypi/rp2040 \
tinyusb/src/portable/renesas/rusb2 \
tinyusb/src/portable/sony/cxd56 \
tinyusb/src/portable/st/stm32_fsdev \
tinyusb/src/portable/st/typec \
tinyusb/src/portable/sunxi \
tinyusb/src/portable/synopsys/dwc2 \
tinyusb/src/portable/template \
tinyusb/src/portable/ti/msp430x5xx \
tinyusb/src/portable/valentyusb/eptri \
tinyusb/src/portable/wch \
tinyusb/src \
tinyusb/src/typec \

